### ISSUE TITLE
Training details

### ISSUE THREAD

**Issue by SimJeg** [Yejin0111/autoPET2022_Blackbean#1]
Hello, 

Congratulations for winning the AutoPET challenge :)  Do you plan to provide your training code ?

What are the main differences compared to the standard nnU-Net 3D pipeline ?
- patch size (192, 192, 192)
- LR = 1e-4
- max_num_features = 512 instead of 390
- anything else ? 

Simon

**Comment by Yejin0111** [comment]
Hi, SimJeg,

The main differences are **Patch size** and **LR**. Compared to the two factors, network architecture has a secondary influence on the final results. 

Jin Ye

**Comment by SimJeg** [comment]
Very interesting, thank you
