### ISSUE TITLE
Input spacing

### ISSUE THREAD

**Issue by SimJeg** [Yejin0111/autoPET2022_Blackbean#2]
Hello,

In your [paper](https://rumc-gcorg-p-public.s3.amazonaws.com/evaluation-supplementary/686/2938ef70-9fee-486f-b171-535128710c8d/autoPET_paper.pdf) I read : 

> the provided CTand PET scans are resampled to 1.500 × 1.0182 × 1.0182 mm

However, the [dataset description](https://autopet.grand-challenge.org/Dataset/) mentions a slice thickness of 2 to 3mm for CT and in the `plans.pkl` file in the checkpoint you provided, I indeed find that `plans['original_spacings']` is always 3.000 × 2.0364 × 2.0364 mm, so there is a ratio of x2.

Now in `process.py`, the `predict_from_folder` function is called with `ratio=None` so the spacing is not modified. Then in `predict.py`, the `predict_cases` function preprocesses the input using `trainer.preprocess_patient` which in turns calls `self.plans['plans_per_stage'][self.stage]['current_spacing']`. For stage = 1, `plans['plans_per_stage'][1]['current_spacing']` is again 3.000 × 2.0364 × 2.0364 mm. So where does 1.500 × 1.0182 × 1.0182 mm appears ?

I am very new to nnU-Net so I guess I missed something, could you help me with this ? 

Simon

**Comment by Yejin0111** [comment]
Thanks for your feedback. 

I checked the data and code, I am sorry I made mistakes in **spacing**. The training spacing and test spacing are fixed to 3.000 × 2.0364 × 2.0364. I will fix the mistake in our paper.

Jin Ye

**Comment by Yejin0111** [comment]
Hi, SimJeg,

Sorry for replying so late and thanks for your feedback.

I checked the data and code, I am sorry I made mistakes in spacing. The training spacing and test spacing are fixed to 3.000 × 2.0364 × 2.0364. I will fix the mistake in our paper.

Jin Ye

**Comment by SimJeg** [comment]
Thanks for your reply !
